# Generated by Django 4.2.15 on 2024-10-31 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('audio', models.FileField(null=True, upload_to='Audios/')),
                ('file_type', models.CharField(blank=True, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(null=True)),
                ('name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audio File Records',
                'ordering': ['name', 'created'],
            },
        ),
    ]
