# Generated by Django 4.2.15 on 2024-10-31 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
