# Generated by Django 4.2.15 on 2025-02-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='text_file',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
