# Generated by Django 4.2.15 on 2024-11-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_audiofile_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFromAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
