# Generated by Django 4.2.15 on 2024-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_textfromaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfromaudio',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
