# Generated by Django 4.2.15 on 2025-02-24 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_textfromaudio_added_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfromaudio',
            name='added',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
