# Generated by Django 4.2.15 on 2024-11-24 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_alter_textfromaudio_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio',
            field=models.FileField(null=True, upload_to='Audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'aac', 'flac', 'ogg'])]),
        ),
    ]
