# Generated by Django 4.2.15 on 2025-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_alter_audiofile_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='text',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
