# Generated by Django 4.2.15 on 2025-01-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_audiofile_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
