# Generated by Django 4.2.15 on 2025-02-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognition', '0007_alter_audiofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='name',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
