# Generated by Django 4.2.15 on 2025-02-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_alter_audiofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'ordering': ['created'], 'verbose_name_plural': 'Audio Files'},
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio',
            new_name='audio_file',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='text',
            new_name='text_file',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='name',
        ),
    ]
