# Generated by Django 4.2.15 on 2024-08-15 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('password', models.TextField(max_length=200)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_registered', models.BooleanField()),
            ],
        ),
    ]
