# Generated by Django 4.2.15 on 2025-02-16 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_groups_users_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_staff',
            new_name='id_admin',
        ),
        migrations.AddField(
            model_name='users',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID'),
        ),
    ]
