# Generated by Django 4.2.15 on 2025-02-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='uploaded_file',
        ),
    ]
