# Generated by Django 4.2.15 on 2024-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_login_email_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
